### ISSUE TITLE
Lookahead not working in OrderedChoice

### ISSUE THREAD

**Issue by vprat** [textX/Arpeggio#96]
Because `And` and `Or` return nothing when parsed, they are ignored by `OrderedChoice`.
```
>>> from arpeggio import *
>>> def expr(): return [ Not("a"), "a" ], Optional("b")
... 
>>> p = ParserPython(expr)
>>> p.debug = True
>>> p.parse("b")
>> Matching rule expr=Sequence at position 0 => *b
   >> Matching rule OrderedChoice in expr at position 0 => *b
      >> Matching rule Not in expr at position 0 => *b
         ?? Try match rule StrMatch(a) in expr at position 0 => *b
         -- No match 'a' at 0 => '*b*'
      <<- Not matched rule Not in expr at position 0 => *b
      ?? Try match rule StrMatch(a) in expr at position 0 => *b
      -- No match 'a' at 0 => '*b*'
   <<- Not matched rule OrderedChoice in expr at position 0 => *b
<<- Not matched rule expr=Sequence in expr at position 0 => *b
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "arpeggio/__init__.py", line 1525, in parse
    self.parse_tree = self._parse()
  File "arpeggio/__init__.py", line 1785, in _parse
    return self.parser_model.parse(self)
  File "arpeggio/__init__.py", line 300, in parse
    result = self._parse(parser)
  File "arpeggio/__init__.py", line 379, in _parse
    result = e.parse(parser)
  File "arpeggio/__init__.py", line 300, in parse
    result = self._parse(parser)
  File "arpeggio/__init__.py", line 432, in _parse
    parser._nm_raise(self, c_pos, parser)
  File "arpeggio/__init__.py", line 1727, in _nm_raise
    raise self.nm
  File "arpeggio/__init__.py", line 418, in _parse
    result = e.parse(parser)
  File "arpeggio/__init__.py", line 798, in parse
    result = self._parse(parser)
  File "arpeggio/__init__.py", line 907, in _parse
    parser._nm_raise(self, c_pos, parser)
  File "arpeggio/__init__.py", line 1727, in _nm_raise
    raise self.nm
  File "arpeggio/__init__.py", line 670, in _parse
    e.parse(parser)
  File "arpeggio/__init__.py", line 798, in parse
    result = self._parse(parser)
  File "arpeggio/__init__.py", line 907, in _parse
    parser._nm_raise(self, c_pos, parser)
  File "arpeggio/__init__.py", line 1727, in _nm_raise
    raise self.nm
arpeggio.NoMatch: Expected 'a' at position (1, 1) => '*b'.
```

**Comment by igordejanovic** [comment]
`Not` and `And` are syntactic predicates. I don't think that they should be used as a sole expressions but as a part of a sequence. Nevertheless, at least what we could do is to report error during parser construction if predicates are used in this way.

**Comment by vprat** [comment]
For comparison, [Ohm](https://ohmjs.org/docs/syntax-reference#lookahead-) says lookahead is _usually_ used as part of a sequence, but it is not mandatory.

Indeed, the string `"b"` is parsed by the following grammar in the [Ohm editor](https://ohmjs.org/editor/):
```
Grammar {
    rule = notaora "b"?
    notaora = ~"a" -- nota
    | "a" -- a
}
```

**Comment by igordejanovic** [comment]
Thanks for the input. I'll investigate. BTW, do you have any real-world example where you would like to use predicates outside of a sequence? I just can't figure out where it would be useful.

**Comment by vprat** [comment]
We had a grammar where this occurred.
Eventually, we managed to rewrite it to avoid the problem, but I am not sure this is always possible.

**Comment by igordejanovic** [comment]
Fixed on the `master` branch.
